-- 89
SELECT RPAD(' ', LEVEL * 3) || ENAME, LEVEL, SAL, JOB
FROM EMP
START WITH ENAME='KING'
CONNECT BY PRIOR EMPNO = MGR;

-- 89-1
SELECT RPAD(' ', LEVEL * 3) || ENAME, LEVEL, SAL, JOB
FROM EMP
WHERE LEVEL = 2
START WITH ENAME = 'KING'
CONNECT BY PRIOR EMPNO=MGR;

-- 90
SELECT RPAD(' ', LEVEL * 3) || ENAME, LEVEL, EMPNO, MGR, SAL, JOB
FROM EMP
START WITH ENAME='KING'
CONNECT BY PRIOR EMPNO = MGR AND ENAME != 'BLAKE';

-- 90-1
SELECT RPAD(' ', LEVEL * 3) || ENAME, LEVEL, EMPNO, MGR, SAL, JOB
FROM EMP
START WITH ENAME='KING'
CONNECT BY PRIOR EMPNO = MGR AND ENAME NOT IN ('SCOTT', 'FORD');

-- 91
SELECT RPAD(' ', LEVEL * 3) || ENAME AS EMPLOYEE,
       LEVEL,
       SAL,
       JOB
FROM EMP
START WITH ENAME='KING'
CONNECT BY PRIOR EMPNO = MGR
ORDER SIBLINGS BY SAL DESC;

-- 91-1
SELECT RPAD(' ', LEVEL * 3) || ENAME AS EMPLOYEE,
       LEVEL,
       SAL,
       JOB
FROM EMP
START WITH ENAME='BLAKE'
CONNECT BY PRIOR EMPNO = MGR
ORDER SIBLINGS BY SAL ASC;

-- 92
SELECT ENAME, SYS_CONNECT_BY_PATH(ENAME, '/') AS PATH
FROM EMP
START WITH ENAME='KING'
CONNECT BY PRIOR EMPNO = MGR;

-- 92-1
SELECT ENAME || '(' || SAL || ')' AS EMPLOYEE,
       SYS_CONNECT_BY_PATH(ENAME || '(' || SAL || ')', '/') AS PATH
FROM EMP
START WITH ENAME='KING'
CONNECT BY PRIOR EMPNO = MGR;

-- 93
CREATE TABLE EMP93 (
                       EMPNO NUMBER(10) NOT NULL,
                       ENAME VARCHAR2(10),
                       SAL NUMBER(10,2),
                       HIREDATE DATE
);

SELECt *
FROM EMP93;

INSERT INTO EMP93 (EMPNO, ENAME, SAL, HIREDATE) VALUES (7788, 'SCOTT', 3000, to_DATE('81/12/21', 'RR/MM/DD'));

DROP TABLE EMP93;

-- 93-1
CREATE TABLE EMP50 (
                       EMPNO NUMBER(10) NOT NULL,
                       ENAME VARCHAR2(10),
                       SAL NUMBER(10,2),
                       JOB VARCHAR2(20),
                       DEPTNO NUMBER(10)
);

SELECT * FROM EMP50;
DROP TABLE EMP50;

-- 94
CREATE GLOBAL TEMPORARY TABLE EMP37
( EMPNO NUMBER(10),
  ENAME VARCHAR2(10),
  SAL   number(10)
) ON COMMIT DELETE ROWS; -- 커밋을 하면 데이터를 지움

INSERT INTO EMP37 VALUES(1111, 'scott', 3000);
INSERT INTO EMP37 VALUES (2222, 'smith', 4000);

SELECT * FROM EMP37;
COMMIT;

-- 94-1
CREATE GLOBAL TEMPORARY TABLE EMP94
( EMPNO NUMBER(10),
  ENAME VARCHAR2(10),
  SAL   number(10)
) ON COMMIT PRESERVE ROWS; -- 세션 종료하면 데이터를 지움