
-- 67
SELECT DEPTNO, SUM(SAL) AS sal
FROM EMP
GROUP BY DEPTNO
UNION ALL 
SELECT TO_NUMBER(NULL), SUM(SAL)
FROM EMP;

-- 67-1
SELECT JOB, SUM(SAL)
FROM EMP 
GROUP BY JOB
UNION ALL
SELECT NULL, SUM(SAL)
FROM EMP;


-- 68
SELECT DEPTNO, SUM(SAL) AS sal
FROM EMP
GROUP BY DEPTNO
UNION ALL 
SELECT NULL, SUM(SAL)
FROM EMP
ORDER BY DEPTNO;

-- 69 
SELECT ENAME, SAL, JOB, DEPTNO 
FROM EMP 
WHERE DEPTNO IN (10, 20)
INTERSECT 
SELECT ENAME, SAL, JOB, DEPTNO 
FROM EMP 
WHERE DEPTNO IN (20, 30);

-- 69-1 
SELECT DEPTNO 
FROM EMP 
INTERSECT
SELECT DEPTNO 
FROM DEPT;

-- 70 
SELECT ENAME, SAL, JOB, DEPTNO 
FROM EMP 
WHERE DEPTNO IN (10, 20) 
MINUS
SELECT ENAME, SAL, JOB, DEPTNO 
FROM EMP 
WHERE DEPTNO IN (20, 30);


-- 71
SELECT ENAME, SAL 
FROM EMP
WHERE SAL > (
	SELECT SAL 
	FROM EMP 
	WHERE ENAME='JONES'
);

-- 71-1 
SELECT ENAME, SAL 
FROM EMP
WHERE HIREDATE > (
			SELECT HIREDATE 
			FROM EMP 
			WHERE ENAME='ALLEN'
	);

-- 72 
SELECT ENAME, SAL 
FROM EMP 
WHERE SAL IN (
	SELECT SAL 
	FROM EMP
	WHERE JOB='SALESMAN'
);

-- 73

SELECT DISTINCT B.ENAME
FROM EMP A JOIN EMP B
ON A.MGR = B.EMPNO;

SELECT ENAME 
FROM EMP 
WHERE EMPNO IN (SELECT MGR FROM EMP)

-- 73-1
-- NOT IN or != ALL  경우 in 안에 있는 값을 AND로 연결하기 떄문에 NULL이 들어가면 T/F 알 수 없기 때문에 결과가 NULL
SELECT ENAME 
FROM EMP 
WHERE EMPNO NOT IN (SELECT NVL(MGR, -1) FROM EMP WHERE MGR IS NOT NULL)

-- 74 EXIST인 경우 메인쿼리 먼저 실행 
SELECT *
FROM DEPT 
WHERE EXISTS (SELECT * 
				FROM EMP
				WHERE EMP.DEPTNO = DEPT.DEPTNO	
				)
				
-- 74-1 
				SELECT *
FROM DEPT 
WHERE NOT EXISTS (SELECT * 
				FROM EMP
				WHERE EMP.DEPTNO = DEPT.DEPTNO	
				)

